version: "3.1"

services:
  confluence:
    image: registry.cn-hangzhou.aliyuncs.com/mengweijin/confluence:latest
    restart: always
    container_name: confluence
    hostname: confluence
    ports:
      - 8090:8090
      - 8091:8091
    links:
      - postgres:postgres
  postgres:
    # confluence官方支持postgres的版本：9.4，9.5，9.6
    image: postgres:9
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: confluence
      POSTGRES_PASSWORD: confluence



