version: "3.1"

services:
  sonarqube:
    image: sonarqube:7.9-community
    restart: always
    container_name: sonarqube
    hostname: sonarqube
    ports:
    - 9000:9000
    links:
    - postgres:postgres
    environment:
      sonar.jdbc.url: jdbc:postgresql://postgres:5432/sonar
  postgres:
    image: postgres:12
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar



