version: "3.1"

services:
  sonarqube:
    image: registry.cn-hangzhou.aliyuncs.com/mengweijin/sonarqube:latest
    restart: always
    container_name: sonarqube
    hostname: sonarqube
    ports:
    - 9000:9000
    links:
    - postgres:postgres
    environment:
      sonar.jdbc.url: jdbc:postgresql://postgres:5432/postgres
  postgres:
    image: postgres:12
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres



