version: "3.1"

services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  adminer:
    image: adminer
    container_name: adminer
    ports:
      -8080:8080


